services:
  meaningful-playlist:
    build: ..
    container_name: meaningful-playlist-app
    env_file: ../.env-local
    ports:
      - '9000:9000'
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis_mp
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: ["redis-server", "--requirepass", "root"]
    restart: unless-stopped

volumes:
  redis-data: